FROM ubuntu:24.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && apt-get install -y \
   build-essential \
   libgl1-mesa-dev \
   cmake \
   ninja-build \
   pkg-config \
   git \
   qt6-base-dev \
   qt6-declarative-dev \
   qt6-tools-dev \
   qt6-serialbus-dev \
   && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV CMAKE_GENERATOR=Ninja

FROM builder AS tester
WORKDIR /app
CMD ["ctest", "--output-on-failure"]